services:
  redis:
    image: redis:7
    container_name: rsl-redis
    ports:
      - "6379:6379"
  
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: rsl-api
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    # container_name: rsl-worker # Имя контейнера. Не нужно, если воркеров может быть несколько
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis