FROM python:3.10.14-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libc-dev \
    libgl1 \
    libglib2.0-0 \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

CMD [ "python3", "-m", "app.worker.worker" ]