# базовый образ с Python 3.10
FROM python:3.10.14-slim

# выбор рабочей директории внутри контейнера
WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libc-dev \
    libgl1 \
    libglib2.0-0 \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

# копируем файл с зависимостями в контейнер
COPY ./requirements.txt .

# устанавливаем зависимости из requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# копируем весь код приложения в контейнер
COPY app ./app

# открываем порт 8000 для API
EXPOSE 8000

# команда для запуска API при старте контейнера
CMD [ "python3", "-m", "app.api.main" ]